###########################################################
# Eureka Client作为服务提供方，没有任何消费时。配置文件相对简单
# 只需要关注心跳续约即可
###########################################################
server:
  port: 8081

spring:
  application:
    name: hello-service

eureka:
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      instanceVersion: 1
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

