########################################
# 单节点Eureka Server
#######################################
server:
  port: 8761

eureka:
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 去除失效服务的时间间隔（毫秒）
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: 127.0.0.1
    # 过期时间，默认90s, 可不配置
    lease-expiration-duration-in-seconds: 15
    # 续约时间，默认30s，可不配置
    lease-renewal-interval-in-seconds: 10
  client:
    # 是否将自己注册到Eureka Server。默认是true，由于自己不需要向Eureka注册信息，所以false
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息，由于单节点，所以不需要同步信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka

spring:
  application:
    name: eurka-server

