###########################################################
# Eureka Client作为消费者时。配置文件需要关注以下几点
# - 注册表拉取时间间隔
# - ribbon重试机制问题
# - ribbon对注册表的缓存问题
# - ribbon连接超时、响应超时
# - Hystrix开启断路器条件的配置
# - Hystrix超时时间（需要配合ribbon的超时时间，响应时间做调整）
# - Hystrix资源隔离相关配置问题（线程池隔离、信号量隔离）
###########################################################

server:
  port: 8091

spring:
  application:
    name: order

eureka:
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 5
  client:
    # 针对新服务上线, Eureka client获取不及时的问题，在测试环境，可以适当提高Client端拉取Server注册信息的频率，默认：30秒
    registry-fetch-interval-seconds: 2
    # 默认false，true的话每次都全量拉取注册表
    disable-delta: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/

feign:
  hystrix:
    # 这里设置为true，所有@FeignClient都会受到Hystrix的影响。
    # 所以我们要权衡我们服务的@FeignClient的情况，来判断这里用true，还是用false比较合适
    enabled: true

hystrix:
  threadpool:
    # 线程池资源隔离
    default:
      # 线程池核心线程数
      coreSize: 10
      # 最大队列长度 -1为无上限，默认使用SynchronousQueue，其他值则使用LinkedBlockingQueue
      maxQueueSize: 1000
      # 队列达到多少时，拒绝后续请求，被拒绝的请求直接走fallback方法。默认是5，这个值必须和maxQueueSize一起使用
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        isolation:
          thread:
            # 请求响应超时，要与ribbon.ReadTimeOut进行配合
            timeoutInMilliseconds: 15000
      metrics:
        rollingStats:
          # 时间窗口 默认10s
          timeInMilliseconds: 10000
      circuitBreaker:
        # 短路10s后，让断路器处于半开状态
        sleepWindowInMilliseconds: 5000
        # 在配置窗口内，达到1次失败就进行跳闸
        requestVolumeThreshold: 2
        # 出错百分比阈值，达到此阈值则短路
        errorThresholdPercentage: 100
      fallback:
        enabled: true

ribbon:
  eureka:
    enabled: true
  hystrix:
    enabled: true
  # 响应超时、连接超时
  ReadTimeout: 10000
  ConnectTimeout: 3000

  ########## 重试机制，开启重试会带来幂等、响应超时等问题，一般关掉 ##########
  #是否所有操作（连接超时、调用异常or超时）都允许重试。默认值为false。  如果设置为true，则非GET请求，只会重试它的连接超时
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

  # Ribbon对注册表也有缓存，所以这里要和 registry-fetch-interval-seconds 一起设置
  ServerListRefreshInterval: 2000
